backend:
  name: git-gateway
  repo: holaplex/careers.holaplex.com
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/uploads
public_folder: uploads
collections:
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Draft mode (does not display on careers index)"
        name: "draftmode"
        widget: "boolean"
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
